name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main  # Change this to your main branch name, if different
      - 2-integrar-doxygen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate Doxygen Documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'docs/'
        doxyfile-path: 'Doxyfile'